// Source: PBZ net banking website
const intentCodes = [
  { code: 'ADMG', title: 'Administracija' },
  { code: 'GVEA', title: 'Austrijski državni zaposlenici, Kategorija A' },
  { code: 'GVEB', title: 'Austrijski državni zaposlenici, Kategorija B' },
  { code: 'GVEC', title: 'Austrijski državni zaposlenici, Kategorija C' },
  { code: 'GVED', title: 'Austrijski državni zaposlenici, Kategorija D' },
  { code: 'BUSB', title: 'Autobusni' },
  { code: 'CPYR', title: 'Autorsko pravo' },
  { code: 'HSPC', title: 'Bolnička njega' },
  { code: 'RDTX', title: 'Cestarina' },
  { code: 'DEPT', title: 'Depozit' },
  { code: 'DERI', title: 'Derivati (izvedenice)' },
  { code: 'FREX', title: 'Devizno tržište' },
  {
    code: 'CGDD',
    title: 'Direktno terećenje nastalo kao rezultat kartične transakcije',
  },
  { code: 'DIVD', title: 'Dividenda' },
  { code: 'BECH', title: 'Dječji doplatak' },
  { code: 'CHAR', title: 'Dobrotvorno plaćanje' },
  { code: 'ETUP', title: 'Doplata e-novca' },
  { code: 'MTUP', title: 'Doplata mobilnog uređaja (bon)' },
  { code: 'GOVI', title: 'Državno osiguranje' },
  { code: 'ENRG', title: 'Energenti' },
  { code: 'CDCD', title: 'Gotovinska isplata' },
  { code: 'CSDB', title: 'Gotovinska isplata' },
  { code: 'TCSC', title: 'Gradske naknade' },
  { code: 'CDCS', title: 'Isplata gotovine s naknadom' },
  { code: 'FAND', title: 'Isplata naknade za elementarne nepogode' },
  { code: 'CSLP', title: 'Isplata socijalnih zajmova društava  banci' },
  { code: 'RHBS', title: 'Isplata za vrijeme profesionalne rehabilitacije' },
  { code: 'GWLT', title: 'Isplata žrtvama rata i invalidima' },
  {
    code: 'ADCS',
    title:
      'Isplate za donacije, sponzorstva, savjetodavne, intelektualne i druge usluge',
  },
  { code: 'PADD', title: 'Izravno terećenje' },
  { code: 'INTE', title: 'Kamata' },
  { code: 'CDDP', title: 'Kartično plaćanje s odgodom' },
  {
    code: 'CDCB',
    title: 'Kartično plaćanje uz gotovinski povrat (Cashback)',
  },
  { code: 'BOCE', title: 'Knjiženje konverzije u Back Office-u' },
  { code: 'POPE', title: 'Knjiženje mjesta kupnje' },
  { code: 'RCKE', title: 'Knjiženje ponovne prezentacije čeka' },
  { code: 'AREN', title: 'Knjiženje računa potraživanja' },
  { code: 'COMC', title: 'Komercijalno plaćanje' },
  { code: 'UBIL', title: 'Komunalne usluge' },
  {
    code: 'COMT',
    title: 'Konsolidirano plaćanje treće strane za račun potrošača.',
  },
  { code: 'SEPI', title: 'Kupnja vrijednosnica (interna)' },
  { code: 'GDDS', title: 'Kupovina-prodaja roba' },
  {
    code: 'GSCB',
    title: 'Kupovina-prodaja roba i usluga uz gotovinski povrat',
  },
  { code: 'GDSV', title: 'Kupovina/prodaja roba i usluga' },
  { code: 'SCVE', title: 'Kupovina/prodaja usluga' },
  { code: 'HLTC', title: 'Kućna njega bolesnika' },
  { code: 'CBLK', title: 'Masovni kliring kartica' },
  { code: 'MDCS', title: 'Medicinske usluge' },
  { code: 'NWCM', title: 'Mrežna komunikacija' },
  { code: 'RENT', title: 'Najam' },
  { code: 'ALLW', title: 'Naknada' },
  { code: 'SSBE', title: 'Naknada socijalnog osiguranja' },
  { code: 'LICF', title: 'Naknada za licencu' },
  { code: 'GFRP', title: 'Naknada za nezaposlene u toku stečaja' },
  { code: 'BENE', title: 'Naknada za nezaposlenost/invaliditet' },
  { code: 'CFEE', title: 'Naknada za poništenje' },
  { code: 'AEMP', title: 'Naknada za zapošljavanje' },
  { code: 'COLL', title: 'Naplata' },
  { code: 'FCOL', title: 'Naplata naknade po kartičnoj transakciji' },
  { code: 'DBTC', title: 'Naplata putem terećenja' },
  { code: 'NOWS', title: 'Nenavedeno' },
  { code: 'IDCP', title: 'Neopozivo plaćanje sa računa debitne kartice' },
  { code: 'ICCP', title: 'Neopozivo plaćanje sa računa kreditne kartice' },
  { code: 'BONU', title: 'Novčana nagrada (bonus).' },
  { code: 'PAYR', title: 'Obračun plaća' },
  { code: 'BLDM', title: 'Održavanje zgrada' },
  { code: 'HEDG', title: 'Omeđivanje rizika (Hedging)' },
  { code: 'CDOC', title: 'Originalno odobrenje' },
  { code: 'PPTI', title: 'Osiguranje imovine' },
  { code: 'LBRI', title: 'Osiguranje iz rada' },
  { code: 'OTHR', title: 'Ostalo' },
  { code: 'CLPR', title: 'Otplata glavnice kredita za automobil' },
  { code: 'HLRP', title: 'Otplata stambenog kredita' },
  { code: 'LOAR', title: 'Otplata zajma' },
  { code: 'ALMY', title: 'Plaćanje alimentacije' },
  { code: 'RCPT', title: 'Plaćanje blagajničke potvrde. (ReceiptPayment)' },
  { code: 'PRCP', title: 'Plaćanje cijene' },
  { code: 'SUPP', title: 'Plaćanje dobavljača' },
  { code: 'CFDI', title: 'Plaćanje dospjele glavnice' },
  { code: 'GOVT', title: 'Plaćanje države' },
  { code: 'PENS', title: 'Plaćanje mirovine' },
  { code: 'DCRD', title: 'Plaćanje na račun debitne kartice.' },
  { code: 'CCRD', title: 'Plaćanje na račun kreditne kartice' },
  { code: 'SALA', title: 'Plaćanje plaće' },
  { code: 'REBT', title: 'Plaćanje popusta/rabata' },
  { code: 'TAXS', title: 'Plaćanje poreza' },
  { code: 'VATX', title: 'Plaćanje poreza na dodatnu vrijednost' },
  { code: 'RINP', title: 'Plaćanje rata koje se ponavljaju' },
  { code: 'IHRP', title: 'Plaćanje rate pri kupnji na otplatu' },
  { code: 'IVPT', title: 'Plaćanje računa' },
  { code: 'CDBL', title: 'Plaćanje računa za kreditnu karticu' },
  { code: 'TREA', title: 'Plaćanje riznice' },
  { code: 'CMDT', title: 'Plaćanje roba' },
  { code: 'INTC', title: 'Plaćanje unutar društva' },
  { code: 'INVS', title: 'Plaćanje za fondove i vrijednosnice' },
  { code: 'PRME', title: 'Plemeniti metali' },
  { code: 'AGRT', title: 'Poljoprivredni transfer' },
  { code: 'INTX', title: 'Porez na dohodak' },
  { code: 'PTXP', title: 'Porez na imovinu' },
  { code: 'NITX', title: 'Porez na neto dohodak' },
  { code: 'ESTX', title: 'Porez na ostavštinu' },
  { code: 'GSTX', title: 'Porez na robu i usluge' },
  { code: 'HSTX', title: 'Porez na stambeni prostor' },
  { code: 'FWLV', title: 'Porez na strane radnike' },
  { code: 'WHLD', title: 'Porez po odbitku' },
  { code: 'BEXP', title: 'Poslovni troškovi' },
  { code: 'REFU', title: 'Povrat' },
  { code: 'TAXR', title: 'Povrat poreza' },
  { code: 'RIMB', title: 'Povrat prethodne pogrešne transakcije' },
  { code: 'OFEE', title: 'Početna naknada (Opening Fee)' },
  { code: 'ADVA', title: 'Predujam' },
  { code: 'INSU', title: 'Premija osiguranja' },
  { code: 'INPC', title: 'Premija osiguranja za vozilo' },
  { code: 'TRPT', title: 'Prepaid cestarina (ENC)' },
  { code: 'SUBS', title: 'Pretplata' },
  { code: 'CASH', title: 'Prijenos gotovine' },
  { code: 'PENO', title: 'Prisilna naplata' },
  { code: 'COMM', title: 'Provizija' },
  { code: 'INSM', title: 'Rata' },
  { code: 'ELEC', title: 'Račun za električnu energiju' },
  { code: 'CBTV', title: 'Račun za kabelsku TV' },
  { code: 'OTLC', title: 'Račun za ostale telekom usluge' },
  { code: 'GASB', title: 'Račun za plin' },
  { code: 'WTER', title: 'Račun za vodu' },
  { code: 'ANNI', title: 'Renta' },
  { code: 'BBSC', title: 'Rodiljna naknada' },
  { code: 'NETT', title: 'Saldiranje (netiranje)' },
  { code: 'CAFI', title: 'Skrbničke naknade (interne)' },
  { code: 'STDY', title: 'Studiranje' },
  { code: 'ROYA', title: 'Tantijeme' },
  { code: 'PHON', title: 'Telefonski račun' },
  { code: 'FERB', title: 'Trajektni' },
  { code: 'DMEQ', title: 'Trajna medicinska pomagala' },
  { code: 'WEBI', title: 'Transakcija inicirana internetom' },
  { code: 'TELI', title: 'Transakcija inicirana telefonom' },
  {
    code: 'HREC',
    title:
      'Transakcija se odnosi na doprinos poslodavca za troškove stanovanja',
  },
  {
    code: 'CBFR',
    title: 'Transakcija se odnosi na kapitalnu štednju za mirovinu',
  },
  {
    code: 'CBFF',
    title: 'Transakcija se odnosi na kapitalnu štednju, općenito',
  },
  { code: 'TRAD', title: 'Trgovinske usluge' },
  { code: 'COST', title: 'Troškovi' },
  { code: 'CPKC', title: 'Troškovi parkiranja' },
  { code: 'TBIL', title: 'Troškovi telekomunikacija' },
  { code: 'NWCH', title: 'Troškovi za mrežu' },
  { code: 'EDUC', title: 'Troškovi školovanja' },
  { code: 'LIMA', title: 'Upravljanje likvidnošću' },
  { code: 'ACCT', title: 'Upravljanje računom' },
  { code: 'ANTS', title: 'Usluge anestezije' },
  { code: 'VIEW', title: 'Usluge oftalmološke skrbi' },
  { code: 'LTCF', title: 'Ustanova dugoročne zdravstvene skrbi' },
  { code: 'ICRF', title: 'Ustanova socijalne skrbi' },
  { code: 'CVCF', title: 'Ustanova za usluge skrbi za rekonvalescente' },
  { code: 'PTSP', title: 'Uvjeti plaćanja' },
  { code: 'MSVC', title: 'Višestruke vrste usluga' },
  { code: 'SECU', title: 'Vrijednosni papiri' },
  { code: 'LOAN', title: 'Zajam' },
  { code: 'FCPM', title: 'Zakašnjele naknade' },
  { code: 'TRFD', title: 'Zaklada' },
  { code: 'CDQC', title: 'Zamjenska gotovina' },
  { code: 'HLTI', title: 'Zdravstveno osiguranje' },
  { code: 'AIRB', title: 'Zračni' },
  { code: 'DNTS', title: 'Zubarske usluge' },
  { code: 'SAVG', title: 'Štednja' },
  { code: 'RLWY', title: 'Željeznički' },
  { code: 'LIFI', title: 'Životno osiguranje' },
];

export const validateIntentCode = (intentCode: string) =>
  intentCodes.map((c) => c.code).includes(intentCode);
